server:
  port: 8095

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
      
info:
  app:
    name: "identity-service"
    description: "E2Rent Identity-Service Application"
    version: "1.0.0"

jwt:
  key: ${APP_JWT_SECRET}
  algorithm: ${APP_JWT_ALGORITHM}
  issuer: ${APP_JWT_ISSUER}
  expiresIn: ${APP_JWT_EXPIRES_IN}